### ISSUE TITLE
Include all speech data from 1867

### ISSUE THREAD

**Issue by fredrik1984** [humlab-swedeb/swedeb-api#35]
We should include all annotated speech data in SweDeb, hence from 1867. The mapping quality of speeches–speakers is lower before 1900 but I still think there is a benefit to include it now. Most likely, the Swerik project will improve the quality and then it is only for Humlab to do an update once or twice a year.

Regarding party filtering: at the top of the list of party names will be the current Riksdag parties (in alphabetical order). Then we can list all other parties (also in alphabetical order, possibly we can also add the start/end year for when a party was represented in the Riksdag).

**Comment by roger-mahler** [comment]
New dataset spanning 1867-202x has now been generated.

- The data reside in folder `/data/swedeb/v1.1.0`.
- The CWB database is named `RIKSPROT_V110_TEST`.

The SweDeb application must be configured accordingly to use the new version.

Note that some changes are needed when switching due to switch from wiki id to swerik id in the underlying metadata.
